openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api

paths:
  /buildings:
    get:
      tags: [ Buildings ]
      operationId: listBuildings
      summary: Получить список зданий
      description: Возвращает список доступных зданий с координатами.
      responses:
        '200':
          description: OK — список зданий получен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBuildingsResponse'
        '400':
          description: Validation Error — входные данные не прошли валидацию.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal Server Error — непредвиденная ошибка на сервере.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /buildings/{id}:
    get:
      tags: [ Buildings ]
      operationId: getBuilding
      summary: Получить информацию о здании
      description: Возвращает данные здания по идентификатору.
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор здания.
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: OK — здание найдено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBuildingResponse'
        '404':
          description: Not Found — здание не найдено.
        '500':
          description: Internal Server Error — непредвиденная ошибка на сервере.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /buildings/search/circle:
    get:
      tags: [ Buildings ]
      operationId: searchBuildingsInRadius
      summary: Геопоиск зданий по радиусу
      description: Находит здания в пределах заданного радиуса от точки.
      parameters:
        - name: latitude
          in: query
          required: true
          description: Центральная широта.
          schema:
            type: number
            format: double
            minimum: -90
            maximum: 90
        - name: longitude
          in: query
          required: true
          description: Центральная долгота.
          schema:
            type: number
            format: double
            minimum: -180
            maximum: 180
        - name: radius
          in: query
          required: true
          description: Радиус поиска в метрах.
          schema:
            type: number
            format: double
            minimum: 1
          example: 500
      responses:
        '200':
          description: OK — найдены здания в радиусе.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBuildingsResponse'
        '400':
          description: Validation Error — входные данные не прошли валидацию.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal Server Error — непредвиденная ошибка на сервере.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    staticApiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: >
        Статический API-ключ, передаваемый в заголовке `X-API-Key`.
  schemas:
    ValidationError:
      type: object
      description: Стандартизированный формат ошибки.
      properties:
        message:
          type: string
          nullable: true
          description: Общее сообщение об ошибке. Обычно приходит или оно или errors.
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ValidationErrorItem'

    ValidationErrorItem:
      type: object
      required: [ message ]
      properties:
        message:
          type: string
          description: Человеческое описание проблемы.
          example: "Имя должно быть не короче 6 символов."
        field:
          type: string
          description: Имя поля, к которому относится ошибка.
          example: name

    Error:
      type: object
      required: [ message ]
      properties:
        message:
          type: string
          description: Человеческое описание проблемы.
          example: "Что то пошло не так."

    Building:
      type: object
      description: Информация о здании с координатами.
      required: [ id, address, latitude, longitude, created_at, updated_at ]
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор здания.
          example: 42
        address:
          type: string
          description: Почтовый адрес здания.
          example: "Москва, ул. Льва Толстого, 16"
        latitude:
          type: number
          format: double
          description: Географическая широта.
          example: 55.733969
        longitude:
          type: number
          format: double
          description: Географическая долгота.
          example: 37.588144
        created_at:
          type: string
          format: date-time
          description: Дата создания записи.
        updated_at:
          type: string
          format: date-time
          description: Дата обновления записи.

    GetBuildingResponse:
      type: object
      description: Ответ с данными одного здания.
      required: [ building ]
      properties:
        building:
          $ref: '#/components/schemas/Building'

    ListBuildingsResponse:
      type: object
      description: Ответ со списком зданий.
      required: [ buildings ]
      properties:
        buildings:
          type: array
          items:
            $ref: '#/components/schemas/Building'
